"""empty message

Revision ID: ce15b67d086d
Revises: None
Create Date: 2016-04-04 19:33:52.654447

"""

# revision identifiers, used by Alembic.
revision = 'ce15b67d086d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('wish_list', sa.Column('url', sa.String(), nullable=True))
    op.drop_constraint(u'wish_list_owner_fkey', 'wish_list', type_='foreignkey')
    op.drop_column('wish_list', 'owner')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'wish_list_owner_fkey', 'wish_list', 'users', ['owner'], ['id'])
    op.drop_column('wish_list', 'url')
    op.drop_column('wish_list', 'thumbnail')
    ### end Alembic commands ###
