"""empty message

Revision ID: f75e44be2074
Revises: ce15b67d086d
Create Date: 2016-04-04 23:43:13.928554

"""

# revision identifiers, used by Alembic.
revision = 'f75e44be2074'
down_revision = 'ce15b67d086d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list', sa.Column('description', sa.String(), nullable=True))
    op.add_column('wish_list', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wish_list', 'users', ['owner'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wish_list', type_='foreignkey')
    op.drop_column('wish_list', 'owner')
    op.drop_column('wish_list', 'description')
    ### end Alembic commands ###
